//! Letter a..r baked weapon defs.

use crate::WeaponClass;

use super::types::{FireImpulseSize, FireMode, MuzzlePolicy, WeaponDef};

pub static WEAPON_TABLE: [WeaponDef; 18] = [
    // a launcher
    WeaponDef {
        letter: b'a',
        class: WeaponClass::Launcher,
        mode: FireMode::Semi,
        t_ready: 0.18,
        rpm: 48.0,
        muzzle_vel: 85.0 / 3.0,
        max_range: 80.0,
        spread_half_deg: 0.5,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 1.15,
            yaw_deg: 0.18,
            back_m: 0.020,
            fall_s: 0.055,
        },
    },
    // b pistol
    WeaponDef {
        letter: b'b',
        class: WeaponClass::Pistol,
        mode: FireMode::Semi,
        t_ready: 0.06,
        rpm: 220.0,
        muzzle_vel: 380.0 / 3.0,
        max_range: 120.0,
        spread_half_deg: 0.4,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.55,
            yaw_deg: 0.14,
            back_m: 0.009,
            fall_s: 0.05,
        },
    },
    // c smg
    WeaponDef {
        letter: b'c',
        class: WeaponClass::Smg,
        mode: FireMode::FullAuto,
        t_ready: 0.08,
        rpm: 700.0,
        muzzle_vel: 420.0 / 3.0,
        max_range: 140.0,
        spread_half_deg: 0.6,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.50,
            yaw_deg: 0.14,
            back_m: 0.007,
            fall_s: 0.055,
        },
    },
    // d AR
    WeaponDef {
        letter: b'd',
        class: WeaponClass::AssaultRifle,
        mode: FireMode::Burst,
        t_ready: 0.12,
        rpm: 600.0,
        muzzle_vel: 650.0 / 3.0,
        max_range: 200.0,
        spread_half_deg: 0.35,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 3,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.55,
            yaw_deg: 0.14,
            back_m: 0.010,
            fall_s: 0.055,
        },
    },
    // e sniper
    WeaponDef {
        letter: b'e',
        class: WeaponClass::SniperRifle,
        mode: FireMode::Semi,
        t_ready: 0.16,
        rpm: 48.0,
        muzzle_vel: 820.0 / 3.0,
        max_range: 300.0,
        spread_half_deg: 0.15,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.85,
            yaw_deg: 0.16,
            back_m: 0.013,
            fall_s: 0.055,
        },
    },
    // f sniper
    WeaponDef {
        letter: b'f',
        class: WeaponClass::SniperRifle,
        mode: FireMode::Semi,
        t_ready: 0.16,
        rpm: 42.0,
        muzzle_vel: 850.0 / 3.0,
        max_range: 320.0,
        spread_half_deg: 0.12,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.85,
            yaw_deg: 0.16,
            back_m: 0.013,
            fall_s: 0.055,
        },
    },
    // g smg
    WeaponDef {
        letter: b'g',
        class: WeaponClass::Smg,
        mode: FireMode::FullAuto,
        t_ready: 0.08,
        rpm: 750.0,
        muzzle_vel: 400.0 / 3.0,
        max_range: 130.0,
        spread_half_deg: 0.65,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.50,
            yaw_deg: 0.14,
            back_m: 0.007,
            fall_s: 0.055,
        },
    },
    // h smg
    WeaponDef {
        letter: b'h',
        class: WeaponClass::Smg,
        mode: FireMode::FullAuto,
        t_ready: 0.08,
        rpm: 720.0,
        muzzle_vel: 410.0 / 3.0,
        max_range: 135.0,
        spread_half_deg: 0.6,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.50,
            yaw_deg: 0.14,
            back_m: 0.007,
            fall_s: 0.055,
        },
    },
    // i pistol alternate
    WeaponDef {
        letter: b'i',
        class: WeaponClass::Pistol,
        mode: FireMode::Semi,
        t_ready: 0.06,
        rpm: 200.0,
        muzzle_vel: 360.0 / 3.0,
        max_range: 110.0,
        spread_half_deg: 0.45,
        muzzle_policy: MuzzlePolicy::Alternate,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.55,
            yaw_deg: 0.14,
            back_m: 0.009,
            fall_s: 0.05,
        },
    },
    // j shotgun all(2) Ã— 3
    WeaponDef {
        letter: b'j',
        class: WeaponClass::Shotgun,
        mode: FireMode::Semi,
        t_ready: 0.10,
        rpm: 90.0,
        muzzle_vel: 380.0 / 3.0,
        max_range: 60.0,
        spread_half_deg: 2.5,
        muzzle_policy: MuzzlePolicy::All,
        pellets: 3,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 1.05,
            yaw_deg: 0.26,
            back_m: 0.018,
            fall_s: 0.055,
        },
    },
    // k shotgun single Ã— 6
    WeaponDef {
        letter: b'k',
        class: WeaponClass::Shotgun,
        mode: FireMode::Semi,
        t_ready: 0.10,
        rpm: 85.0,
        muzzle_vel: 370.0 / 3.0,
        max_range: 55.0,
        spread_half_deg: 3.0,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 6,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 1.05,
            yaw_deg: 0.26,
            back_m: 0.018,
            fall_s: 0.055,
        },
    },
    // l smg alternate
    WeaponDef {
        letter: b'l',
        class: WeaponClass::Smg,
        mode: FireMode::FullAuto,
        t_ready: 0.08,
        rpm: 680.0,
        muzzle_vel: 415.0 / 3.0,
        max_range: 135.0,
        spread_half_deg: 0.6,
        muzzle_policy: MuzzlePolicy::Alternate,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.50,
            yaw_deg: 0.14,
            back_m: 0.007,
            fall_s: 0.055,
        },
    },
    // m smg
    WeaponDef {
        letter: b'm',
        class: WeaponClass::Smg,
        mode: FireMode::FullAuto,
        t_ready: 0.08,
        rpm: 710.0,
        muzzle_vel: 405.0 / 3.0,
        max_range: 130.0,
        spread_half_deg: 0.65,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.50,
            yaw_deg: 0.14,
            back_m: 0.007,
            fall_s: 0.055,
        },
    },
    // n AR
    WeaponDef {
        letter: b'n',
        class: WeaponClass::AssaultRifle,
        mode: FireMode::Burst,
        t_ready: 0.12,
        rpm: 580.0,
        muzzle_vel: 640.0 / 3.0,
        max_range: 200.0,
        spread_half_deg: 0.35,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 3,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.55,
            yaw_deg: 0.14,
            back_m: 0.010,
            fall_s: 0.055,
        },
    },
    // o shotgun all(4) Ã— 2
    WeaponDef {
        letter: b'o',
        class: WeaponClass::Shotgun,
        mode: FireMode::Semi,
        t_ready: 0.10,
        rpm: 75.0,
        muzzle_vel: 360.0 / 3.0,
        max_range: 50.0,
        spread_half_deg: 3.5,
        muzzle_policy: MuzzlePolicy::All,
        pellets: 2,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 1.05,
            yaw_deg: 0.26,
            back_m: 0.018,
            fall_s: 0.055,
        },
    },
    // p smg
    WeaponDef {
        letter: b'p',
        class: WeaponClass::Smg,
        mode: FireMode::FullAuto,
        t_ready: 0.08,
        rpm: 780.0,
        muzzle_vel: 430.0 / 3.0,
        max_range: 140.0,
        spread_half_deg: 0.55,
        muzzle_policy: MuzzlePolicy::Alternate,
        pellets: 1,
        burst_count: 0,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.50,
            yaw_deg: 0.14,
            back_m: 0.007,
            fall_s: 0.055,
        },
    },
    // q AR alternate
    WeaponDef {
        letter: b'q',
        class: WeaponClass::AssaultRifle,
        mode: FireMode::Burst,
        t_ready: 0.12,
        rpm: 560.0,
        muzzle_vel: 630.0 / 3.0,
        max_range: 195.0,
        spread_half_deg: 0.4,
        muzzle_policy: MuzzlePolicy::Alternate,
        pellets: 1,
        burst_count: 3,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.55,
            yaw_deg: 0.14,
            back_m: 0.010,
            fall_s: 0.055,
        },
    },
    // r AR
    WeaponDef {
        letter: b'r',
        class: WeaponClass::AssaultRifle,
        mode: FireMode::Burst,
        t_ready: 0.12,
        rpm: 590.0,
        muzzle_vel: 645.0 / 3.0,
        max_range: 200.0,
        spread_half_deg: 0.35,
        muzzle_policy: MuzzlePolicy::Single,
        pellets: 1,
        burst_count: 3,
        fire_impulse: FireImpulseSize {
            pitch_deg: 0.55,
            yaw_deg: 0.14,
            back_m: 0.010,
            fall_s: 0.055,
        },
    },
];

/// Look up a letter's weapon def (`a`â€¦`r`).
pub fn weapon_def(letter: u8) -> Option<&'static WeaponDef> {
    let i = (letter as usize).checked_sub(b'a' as usize)?;
    WEAPON_TABLE.get(i).filter(|d| d.letter == letter)
}
